# frozen_string_literal: true

source "https://rubygems.org"

gem "test-kitchen"
gem "kitchen-dokken"
gem "kitchen-inspec"
gem "inspec-core", ">= 5", "< 6"
gem "rspec", "~> 3.12"
gem "chefspec", "~> 9.3"
gem "chef", "~> 18.10"
